<?php

return [
    'guard_name' => 'web',

    'super_admin_role' => 'admin',

    'roles' => [
        'admin' => [
            'label' => 'Admin',
            'permissions' => ['*'],
        ],
        'lecturer' => [
            'label' => 'Lecturer',
            'permissions' => [
                'dashboard.view',
                'identity.users.view',
                'courses.view',
                'courses.create',
                'courses.update',
                'courses.publish',
                'courses.assign-trainer',
                'courses.manage-enrollments',
                'course_sections.view',
                'course_sections.create',
                'course_sections.update',
                'course_sections.delete',
                'lessons.view',
                'lessons.create',
                'lessons.update',
                'lessons.delete',
                'enrollments.view',
                'payments.view',
                'payments.collect',
                'payments.mark-paid',
                'assignments.view',
                'assignments.create',
                'assignments.grade',
                'assignments.update',
                'assignments.delete',
                'posts.view',
                'posts.create',
                'posts.update',
                'posts.publish',
                'queries.view',
                'queries.reply',
                'queries.resolve',
                'documents.view',
                'documents.upload',
            ],
        ],
        'student' => [
            'label' => 'Student',
            'permissions' => [
                'dashboard.view',
                'courses.view',
                'lessons.view',
                'lessons.complete',
                'enrollments.create',
                'enrollments.view-own',
                'enrollments.progress',
                'assignments.view',
                'assignments.submit',
                'posts.view',
                'posts.create-own',
                'queries.create',
                'queries.view-own',
                'queries.reply-own',
                'documents.view-own',
                'documents.upload-own',
                'payments.view-own',
            ],
        ],
    ],

    'modules' => [
        'dashboard' => ['view'],
        'identity' => [
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'roles.view',
            'roles.assign',
        ],
        'courses' => [
            'view',
            'create',
            'update',
            'delete',
            'publish',
            'assign-trainer',
            'manage-enrollments',
        ],
        'course_sections' => [
            'view',
            'create',
            'update',
            'delete',
        ],
        'lessons' => [
            'view',
            'create',
            'update',
            'delete',
            'complete',
        ],
        'enrollments' => [
            'view',
            'create',
            'view-own',
            'update',
            'progress',
        ],
        'assignments' => [
            'view',
            'create',
            'submit',
            'grade',
            'update',
            'delete',
        ],
        'payments' => [
            'view',
            'view-own',
            'create',
            'collect',
            'refund',
            'mark-paid',
        ],
        'posts' => ['view', 'create', 'create-own', 'update', 'delete', 'publish'],
        'queries' => [
            'view',
            'view-own',
            'create',
            'reply',
            'reply-own',
            'assign',
            'resolve',
            'escalate',
        ],
        'development_requests' => [
            'view',
            'update',
            'delete',
            'quote',
        ],
        'documents' => ['view', 'view-own', 'upload', 'upload-own', 'delete'],
    ],
];
